DROP TABLE GALLERY;
CREATE TABLE GALLERY
(
	NO NUMBER PRIMARY KEY,
	WRITER VARCHAR2(32),
	TITLE VARCHAR2(100),
	CONTENT VARCHAR2(4000),
	POSTDATE DATE,
	LASTMODIFIED DATE,
	IP VARCHAR2(100),
	HIT NUMBER,
	FILENAME VARCHAR2(300)  -- 이미지 파일명
);
ALTER TABLE GALLERY ADD CONSTRAINT GALLERY_MEMBER_FK FOREIGN KEY(WRITER) REFERENCES MEMBER(ID);
DROP SEQUENCE GALLERY_SEQ;
CREATE SEQUENCE GALLERY_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;