DROP TABLE MEMBER;
CREATE TABLE MEMBER
(
	NO NUMBER PRIMARY KEY,
	ID VARCHAR2(32) NOT NULL UNIQUE,
	PW VARCHAR2(64) NOT NULL,  -- 암호화된 비밀번호
	NAME VARCHAR2(64),
	TEL VARCHAR2(64),
	EMAIL VARCHAR2(100) NOT NULL,
	ADDRESS VARCHAR2(100),
	REGDATE DATE,
	STATUS NUMBER NOT NULL  -- 정상: 1, 탈퇴: 0
);
DROP SEQUENCE MEMBER_SEQ;
CREATE SEQUENCE MEMBER_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;
insert INTO MEMBER values (member_seq.nextval, 'admin', '1111', '관리자', '010-1111-1111', 'admin@home.com', '서울시', SYSDATE, 1);
select * from member;